
SkadaDB = {
	["hasUpgraded"] = true,
	["profileKeys"] = {
		["Sergath - Lost Isles (US)"] = "Default",
		["Sergath - Level 100 PvE"] = "Default",
		["Sergath - Gilneas (US)"] = "Default",
		["Sergath - Beta Leveling Realm 02"] = "Default",
		["Sergath - Level 100 PvP"] = "Default",
	},
	["profiles"] = {
		["Default"] = {
			["windows"] = {
				{
					["set"] = "total",
					["y"] = 74.00045013427736,
					["x"] = -13.0003662109375,
					["bartexture"] = "Blizzard Raid Bar",
					["point"] = "BOTTOMRIGHT",
					["mode"] = "Healing",
				}, -- [1]
				{
					["titleset"] = true,
					["barheight"] = 15,
					["classicons"] = true,
					["barslocked"] = false,
					["clickthrough"] = false,
					["wipemode"] = "",
					["set"] = "current",
					["hidden"] = false,
					["y"] = 83.00022888183594,
					["barfont"] = "Accidental Presidency",
					["title"] = {
						["color"] = {
							["a"] = 0.8,
							["r"] = 0.1,
							["g"] = 0.1,
							["b"] = 0.3,
						},
						["bordertexture"] = "None",
						["font"] = "Accidental Presidency",
						["borderthickness"] = 2,
						["fontsize"] = 11,
						["fontflags"] = "",
						["height"] = 15,
						["margin"] = 0,
						["texture"] = "Aluminium",
					},
					["display"] = "bar",
					["barfontflags"] = "",
					["classcolortext"] = false,
					["barbgcolor"] = {
						["a"] = 0.6,
						["r"] = 0.3,
						["g"] = 0.3,
						["b"] = 0.3,
					},
					["barcolor"] = {
						["a"] = 1,
						["r"] = 0.3,
						["g"] = 0.3,
						["b"] = 0.8,
					},
					["returnaftercombat"] = false,
					["barorientation"] = 1,
					["snapto"] = true,
					["mode"] = "Damage",
					["point"] = "BOTTOMRIGHT",
					["bartexture"] = "Blizzard Raid Bar",
					["barwidth"] = 232.0000152587891,
					["barspacing"] = 0,
					["reversegrowth"] = false,
					["x"] = -258.9998779296875,
					["scale"] = 1,
					["barfontsize"] = 11,
					["enabletitle"] = true,
					["classcolorbars"] = true,
					["buttons"] = {
						["segment"] = true,
						["menu"] = true,
						["mode"] = true,
						["report"] = true,
						["reset"] = true,
					},
					["modeincombat"] = "",
					["name"] = "DMG",
					["background"] = {
						["borderthickness"] = 0,
						["color"] = {
							["a"] = 0.2,
							["r"] = 0,
							["g"] = 0,
							["b"] = 0.5,
						},
						["height"] = 191,
						["bordertexture"] = "None",
						["margin"] = 0,
						["texture"] = "Solid",
					},
				}, -- [2]
			},
		},
	},
}
